"""Response schema for the /coach endpoint (see app/services/coaching.py)."""

from pydantic import BaseModel, Field

from app.services.coaching import SUPPORTED_LANGUAGES


class CoachResponse(BaseModel):
    success: bool = True
    assessment: str = Field(
        description="Overall natural-language assessment of the take, in "
        "`lang`, generated by a locally-run Ollama model strictly from "
        "this app's own measured facts -- see app/services/coaching.py"
    )
    suggestion: str = Field(
        default="",
        description="Concrete practice suggestion for the single biggest "
        "issue found, in `lang`. Empty string when the model had nothing "
        "notable to suggest.",
    )
    lang: str = Field(
        description=f"Language the comment was written in. One of: "
        f"{', '.join(SUPPORTED_LANGUAGES)}"
    )
