"""Response schema for the /coach endpoint (see app/services/coaching.py)."""

from pydantic import BaseModel, Field

from app.services.coaching import SUPPORTED_LANGUAGES


class CoachResponse(BaseModel):
    success: bool = True
    assessment: str = Field(
        description="Overall natural-language assessment of the take, in "
        "`lang`, generated by a locally-run Ollama model strictly from "
        "this app's own measured facts -- see app/services/coaching.py"
    )
    suggestion: str = Field(
        default="",
        description="Concrete practice suggestion for the single biggest "
        "issue found, in `lang`. Empty string when the model had nothing "
        "notable to suggest.",
    )
    lang: str = Field(
        description=f"Language the comment was written in. One of: "
        f"{', '.join(SUPPORTED_LANGUAGES)}"
    )


class CategoryGuideResponse(BaseModel):
    success: bool = True
    category_name: str = Field(description="Name of the study category/topic")
    lang: str = Field(description="Target language for the guide (jp, en, ko, tw, vi)")
    guide: str = Field(description="1-sentence learning instruction/explanation generated by Ollama AI")


class TextGuideResponse(BaseModel):
    success: bool = True
    text: str = Field(description="The target Japanese text being analyzed")
    lang: str = Field(description="Target language for the reading guide (jp, en, ko, tw, vi)")
    guide: str = Field(description="Detailed step-by-step reading and pronunciation guide generated by Ollama AI")


